NT_STATUS_NOT_FOUND => name cannot be resolved.
thomasmauerer/hassio-addons pull request #136
Opened 2023-02-08 15:05 UTC by SkyLined

I used a name that could not be resolved and got this error, so I thought I would provide a better error message.

2023-02-08 18:05 UTC, thomasmauerer commented
Thanks for the PR. Please check my two little comments.

2023-02-08 18:07 UTC, thomasmauerer requested changes

2023-02-08 18:07 UTC, thomasmauerer commented on samba-backup/rootfs/scripts/precheck.sh
> +            bashio::log.fatal "The provided host cannot be found. Please check your config and network."
Please change the second sentence to "If you've specified a DNS name, please try using an IP address instead."
I guess we can make a more concrete suggestion in this case.

2023-02-08 18:07 UTC, thomasmauerer commented on samba-backup/rootfs/scripts/precheck.sh
>          if [[ "$result" =~ "NT_STATUS_HOST_UNREACHABLE" ]]; then
Change this to elif, otherwise the last else block will additionally execute.

2023-02-21 08:57 UTC, SkyLined commented
These changes makes sense. I assume I do not need to start all over and can just make changes to my existing PR but I cannot seem to find out how to do that.

2023-02-21 09:33 UTC, thomasmauerer commented
Yes, you can. You just need to push more commits to your patch-1 branch.

2023-02-21 19:04 UTC, SkyLined commented
TIL. Thanks, in hindsight it always seems obvious.

2023-02-21 19:33 UTC, thomasmauerer approved these changes

2023-02-21 19:33 UTC, merged

2023-02-21 19:34 UTC, thomasmauerer commented
Looks good, thanks.